name: "PlantUML diagram generator"
description: |
  Generate PlantUML diagrams with always up to date PlantUML
author: "@holowinski"

branding:
  icon: "bar-chart-2"
  color: "white"

inputs:
  args:
    description: "Arguments for PlantUML"
    required: true
    default: "-h"

runs:
  using: "docker"
  image: "docker://dstockhammer/plantuml:latest"
  args:
    - ${{ inputs.args }}
