name: "PlantUML diagram generator"
description: |
  Generate PlantUML diagrams with always up to date PlantUML
  Forked from https://github.com/holowinski/plantuml-github-action
author: "@babakontheweb"

branding:
  icon: "bar-chart-2"
  color: "white"

inputs:
  args:
    description: "Arguments for PlantUML"
    required: true
    default: "-h"

runs:
  using: "docker"
  image: "docker://plantuml/plantuml:latest"
  args:
    - ${{ inputs.args }}
